[build]
  publish = "."

[[headers]]
  for = "/data/*.geojson"
  [headers.values]
    Content-Type = "application/geo+json"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
